# -*- coding: utf-8 -*-
EN = {
"Weiß": "White", "Schwarz": "Black",
"PGN konnte nicht gelesen werden: {e}": "Could not read the PGN: {e}",
"In der PGN wurden keine Züge gefunden.": "No moves found in the PGN.",
"Bitte eine PGN oder FEN einfügen.": "Please paste a PGN or FEN.",
"Ungültige FEN: {e}": "Invalid FEN: {e}",
"Brillant!!": "Brilliant!!", "Großartig!": "Great move!",
"Du": "You", "denkt …": "thinking …", "du": "you", "Genauigkeit": "Accuracy",
"Matt in {n} ausgelassen": "Missed mate in {n}",
"{piece} auf {sq}": "{piece} on {sq}", "Material": "Material",
"{what} wird geopfert – und Stockfish bestätigt: Das Opfer funktioniert.": "{what} is sacrificed – and Stockfish confirms the sacrifice works.",
"Bewertung danach {ev}.": "Evaluation after the move: {ev}.",
"Der einzige Zug, der den Vorteil hält.": "The only move that keeps the advantage.",
"Der einzige Zug, der die Stellung im Gleichgewicht hält.": "The only move that keeps the balance.",
"Der einzige Zug, der noch Widerstand leistet.": "The only move that keeps up the fight.",
"Der zweitbeste Zug {m} wäre klar schlechter.": "The second-best move {m} would be clearly worse.",
"Genau der Zug, den Stockfish empfiehlt. Bewertung {ev}.": "Exactly the move Stockfish recommends. Evaluation {ev}.",
"Fast so stark wie {m} ({ev}).": "Almost as strong as {m} ({ev}).",
"Solide. Etwas genauer war {m} ({ev}).": "Solid. {m} ({ev}) was a little more precise.",
"Bekannte Eröffnungstheorie": "Known opening theory",
"Der einzige legale Zug.": "The only legal move.",
"Stark war {m} ({ev}). Gewinnchance −{loss} %.": "{m} ({ev}) was strong. Winning chances −{loss}%.",
"Die Widerlegung: {pv}.": "The refutation: {pv}.",
"Besser war {m} ({ev}). Gewinnchance −{loss} %.": "{m} ({ev}) was better. Winning chances −{loss}%.",
"Schwarz gewinnt": "Black wins", "Weiß gewinnt": "White wins", "Remis": "Draw",
"Schachmatt": "Checkmate", "Patt": "Stalemate", "Ungenügendes Material": "Insufficient material",
"Starte über „Neue Partie gegen KI“ die nächste Runde.": "Start the next round with “New game vs. AI”.",
"Ausgangsstellung": "Starting position", "Mach einen Zug": "Make a move",
"Blättere mit ← → durch die Partie; jeder Zug bekommt seine Bewertung.": "Use ← → to step through the game; every move gets its rating.",
"Zieh eine Figur auf dem Brett. Stockfish bewertet jeden Zug sofort – von brillant (!!) bis Patzer (??).": "Move a piece on the board. Stockfish rates every move instantly – from brilliant (!!) to blunder (??).",
"Stockfish empfiehlt hier {m}.": "Stockfish recommends {m} here.",
"Stockfish bewertet den Zug …": "Stockfish is rating the move …",
"Wartet auf die Engine …": "Waiting for the engine …",
"Gewinnchance des ziehenden Spielers: mit dem besten Zug → mit dem gespielten Zug": "Winning chances of the player to move: with the best move → with the move played",
"Gewinnchance {b} % → {a} %": "Winning chances {b}% → {a}%",
"Zug teilen": "Share move", "Antwort der KI:": "AI reply:",
"Matt": "Mate", "versteckt": "hidden", "KI am Zug": "AI to move",
"Hinweise sind aus. Schalte sie oben unter „Hinweise zeigen“ ein.": "Hints are off. Turn on “Show hints” above.",
"rechnet …": "thinking …",
"Stockfish konnte nicht geladen werden.": "Stockfish could not be loaded.",
"Prüfe die Internetverbindung und tippe auf „Nochmal versuchen“.": "Check your internet connection and tap “Try again”.",
"Nochmal versuchen": "Try again", "Details: {d}": "Details: {d}",
"Lade {x} … ({s} s, beim ersten Mal ca. 7 MB)": "Loading {x} … ({s} s, about 7 MB the first time)",
"Stockfish rechnet …": "Stockfish is thinking …", "Tiefe {d}": "Depth {d}", "Zug ausführen": "Play this move",
"Noch keine Züge. Zieh auf dem Brett oder lade über „Partie laden“ eine Partie.": "No moves yet. Move on the board or load a game with “Load game”.",
"wird bewertet": "being rated", "automatisches Review aus": "automatic review off",
"fertig · Tiefe {d}": "done · depth {d}", "analysiert {a} / {b}": "analysed {a} / {b}",
"Bewertungsverlauf der Partie": "Evaluation graph of the game",
"stark": "strong", "gut": "good", "okay": "okay", "schwach": "weak",
"Restzeit nach dem Zug": "Clock after the move",
"Noch keine Schlüsselmomente – sie erscheinen, sobald die Züge bewertet sind.": "No key moments yet – they appear once the moves are rated.",
"Ø Bedenkzeit pro Zug": "Avg. time per move", "Fehler in Zeitnot": "Errors in time trouble", "Fehler nach ≤ 3 s": "Errors after ≤ 3 s",
"Keine Fehler von {c} zum Trainieren": "No mistakes by {c} to practise",
"Fehler-Training nach der Analyse": "Mistake training after the analysis",
"Geladene Partie ab Zug {n} weiterspielen": "Continue the loaded game from move {n}",
"Meine Fehler trainieren ({n})": "Practise my mistakes ({n})",
"Fehler von {c} trainieren ({n})": "Practise {c}'s mistakes ({n})",
"{m} ist der beste Zug!": "{m} is the best move!",
"{m} ist genauso gut – gelöst!": "{m} is just as good – solved!",
"{m} war der Zug aus der Partie. Such weiter.": "{m} was the game move. Keep looking.",
"{m} kostet {l} % Gewinnchance. Versuch es nochmal.": "{m} costs {l}% winning chances. Try again.",
"Lösung: {m}.": "Solution: {m}.",
"Das Tageslimit der kostenlosen Version ist erreicht. Mit Pro trainierst du unbegrenzt.": "You've reached today's free limit. Pro gives you unlimited training.",
"Training beendet": "Training complete",
"{a} von {b} auf Anhieb gelöst.": "{a} of {b} solved on the first try.",
"Pro holen": "Get Pro", "Weiter trainieren": "Keep training", "Nochmal": "Again", "Beenden": "Finish",
"Zurück zur Partie": "Back to the game", "Tipp:": "Hint:", "Thema:": "Theme:",
"Stockfish prüft …": "Stockfish is checking …",
"Taktik-Trainer · {a} von {b}": "Tactics trainer · {a} of {b}",
"Fehler-Training · {a} von {b}": "Mistake training · {a} of {b}",
"In der Partie kam {m} ({k}). Finde einen besseren Zug für {c}.": "The game continued {m} ({k}). Find a better move for {c}.",
"Nächste Aufgabe": "Next puzzle", "Auswertung": "Summary", "Tipp": "Hint", "Lösung zeigen": "Show solution", "Überspringen": "Skip",
"im Training verborgen": "hidden during training", "Während des Trainings ausgeblendet.": "Hidden during training.",
"fällig": "due", "gelernt": "learned", "gesamt": "total",
"Noch keine Aufgaben. Analysiere deine Partien unter „Insights“ oder lade eine Partie – deine Fehler werden automatisch zu Aufgaben.": "No puzzles yet. Analyse your games under “Insights” or load a game – your mistakes become puzzles automatically.",
"Alles erledigt. Die nächste Wiederholung ist am {d} fällig.": "All done. The next review is due on {d}.",
"Jede Aufgabe ist eine Stellung aus deinen eigenen Partien. Gelöste Aufgaben kommen nach 1, 3, 7, 14 … Tagen wieder.": "Every puzzle is a position from your own games. Solved puzzles come back after 1, 3, 7, 14 … days.",
"Kostenlos: noch {n} Aufgaben heute.": "Free: {n} puzzles left today.",
"Diese Seite darf keine Verbindung zu {s} aufbauen. Öffne Zugradar über die eigene Website oder lokal (siehe README). Alternativ: PGN einfügen.": "This page is not allowed to connect to {s}. Open Zugradar on its own website or locally (see README). Or paste a PGN.",
"Benutzer nicht gefunden.": "User not found.",
"Zu viele Anfragen – bitte eine Minute warten.": "Too many requests – please wait a minute.",
"Keine Verbindung zu {s}.": "No connection to {s}.",
"Bitte einen Benutzernamen eingeben.": "Please enter a username.",
"Unbekannter Fehler.": "Unknown error.",
"Bitte deinen Benutzernamen eingeben.": "Please enter your username.",
"Lade Partien von {s} …": "Loading games from {s} …",
"{n} beendete Partien von {u}.": "{n} finished games by {u}.",
"Keine beendeten Partien gefunden.": "No finished games found.",
"Fernschach": "Daily", "S": "W", "Sieg": "Win", "N": "L", "Niederlage": "Loss", "R": "D",
"vs.": "vs.", "mit Weiß": "as White", "mit Schwarz": "as Black", "Analysieren": "Analyse",
"Auto-Import · {u}": "Auto-import · {u}",
"Zuletzt geprüft {d} – keine neue Partie.": "Last checked {d} – no new game.",
"Neue Partie verfügbar – öffne „Partie laden“, um sie zu analysieren.": "New game available – open “Load game” to analyse it.",
"Neue Partie geladen": "New game loaded",
"Neue Partie automatisch geladen: {d}.": "New game loaded automatically: {d}.",
"Gib deinen Benutzernamen ein – dann analysiert Zugradar deine letzten Partien.": "Enter your username – then Zugradar analyses your recent games.",
"Fertig: {a} Partien neu analysiert, {b} waren schon analysiert.": "Done: {a} games analysed, {b} were already analysed.",
"Abgebrochen.": "Cancelled.",
"Nicht lesbar: {n} Partie(n).": "Could not read {n} game(s).",
"Aus {n} analysierten Partien{u}.": "From {n} analysed games{u}.",
"von {u}": "by {u}",
"Noch keine Daten – starte mit deinen letzten Partien.": "No data yet – start with your recent games.",
"Analysiere Partie {a} von {b} …": "Analysing game {a} of {b} …",
"So füllst du deine Insights": "How to fill your insights",
"Unter „Partie laden → Meine Partien“ deinen chess.com- oder lichess-Namen eintragen.": "Enter your chess.com or lichess username under “Load game → My games”.",
"Hier auf „Partien analysieren“ tippen. Stockfish bewertet jede Partie im Hintergrund.": "Tap “Analyse games” here. Stockfish rates every game in the background.",
"Deine Baustellen erscheinen hier, deine Fehler werden zu Aufgaben im Trainer.": "Your weak spots appear here, and your mistakes become puzzles in the trainer.",
"Benutzernamen eintragen": "Enter username",
"Kostenlos siehst du Insights über deine letzten {n} Partien. Pro wertet bis zu {m} aus.": "Free shows insights for your last {n} games. Pro analyses up to {m}.",
"zu den 5 Partien davor": "vs. the 5 games before",
"Ø Genauigkeit": "Avg. accuracy", "Punkte": "Score", "{w} S · {d} R · {l} N": "{w} W · {d} D · {l} L",
"Patzer pro Partie": "Blunders per game", "Fehler: {m} · Verpasst: {x}": "Mistakes: {m} · Misses: {x}",
"Brillante Züge": "Brilliant moves", "Großartig: {g}": "Great: {g}",
"Deine drei Baustellen": "Your three weak spots",
"Keine klare Schwäche erkennbar – analysiere mehr Partien für ein genaueres Bild.": "No clear weakness yet – analyse more games for a sharper picture.",
"Im Trainer üben": "Practise in the trainer", "Genauigkeit pro Partie": "Accuracy per game",
"Phasen": "Phases", "Eröffnung": "Opening", "Mittelspiel": "Middlegame", "Endspiel": "Endgame",
"Ø Genauigkeit deiner Züge je Partiephase.": "Average accuracy of your moves per game phase.",
"Stärken": "Strengths",
"Dein bestes Spiel zeigst du im {p} ({a} %).": "You play your best chess in the {p} ({a}%).",
"{name} mit {c}: {s} der Punkte.": "{name} as {c}: {s} of the points.",
"{n} brillante Züge gefunden.": "{n} brilliant moves found.",
"Fehlermuster": "Mistake patterns", "Noch keine Fehler mit erkennbarem Muster.": "No mistakes with a clear pattern yet.",
"Bei {n} eigenen Fehlern, Patzern und verpassten Chancen.": "Across {n} of your mistakes, blunders and misses.",
"Eröffnungen": "Openings", "Analysierte Partien": "Analysed games", "Noch keine Eröffnungen erkannt.": "No openings recognised yet.",
"Farbe": "Colour", "Partien": "Games",
"pro Monat": "per month", "pro Jahr": "per year", "beliebt": "popular", "einmalig, für immer": "one-time, forever",
"Pro ist aktiv{e}. Schlüssel {k}.": "Pro is active{e}. Key {k}.",
"Zuletzt offline geprüft.": "Last checked while offline.",
"Dein Test läuft bis {d}.": "Your trial runs until {d}.",
"Dein Test ist abgelaufen.": "Your trial has ended.",
"Pro-Test · {n} T.": "Pro trial · {n} d",
"Bitte den vollständigen Lizenzschlüssel eingeben.": "Please enter the full licence key.",
"Dieser Schlüssel gehört zu einem anderen Produkt.": "This key belongs to a different product.",
"Dieser Schlüssel ist nicht aktiv.": "This key is not active.",
"Lizenzserver nicht erreichbar. Prüfe die Verbindung und versuche es erneut.": "Licence server unreachable. Check your connection and try again.",
"Der Schlüssel wurde nicht angenommen.": "The key was not accepted.",
"Brillanter Zug!!": "Brilliant move!!", "Großartiger Zug!": "Great move!",
"Analysiert mit {b} · {u}": "Analysed with {b} · {u}",
"Partie-Review": "Game review",
"bereit": "ready", "KI zieht": "AI moving", "Serie": "batch", "Review": "review", "live": "live",
"Engine nicht geladen – tippen für neuen Versuch": "Engine not loaded – tap to retry",
"Lade {x} …": "Loading {x} …",
"Für den Auto-Import erst den Benutzernamen eingeben.": "Enter your username first to use auto-import.",
"Auto-Import aktiv: Zugradar prüft jede Minute auf neue, beendete Partien.": "Auto-import on: Zugradar checks for new finished games every minute.",
"Kopieren wurde blockiert – die PGN ist markiert, kopiere sie mit Strg+C.": "Copying was blocked – the PGN is selected, copy it with Ctrl+C.",
"PGN kopiert (mit Bewertungen).": "PGN copied (with ratings).",
"Der Shop ist noch nicht verbunden (checkoutUrl in src/config.js).": "The shop is not connected yet (checkoutUrl in src/config.js).",
"Nach dem Kauf bekommst du einen Lizenzschlüssel per E-Mail. Trag ihn unten ein.": "After buying you'll get a licence key by email. Enter it below.",
"Test gestartet – viel Spaß mit Pro!": "Trial started – enjoy Pro!",
"Prüfe Schlüssel …": "Checking key …",
"Pro ist freigeschaltet. Danke für deine Unterstützung!": "Pro is unlocked. Thanks for your support!",
"Anfänger (~800)": "Beginner (~800)", "Gelegenheitsspieler (~1350)": "Casual (~1350)", "Vereinsspieler (~1700)": "Club player (~1700)",
"Stark (~2000)": "Strong (~2000)", "Experte (~2300)": "Expert (~2300)", "Meister (~2600)": "Master (~2600)",
"Großmeister (~2900)": "Grandmaster (~2900)", "Maximal (volle Stärke)": "Maximum (full strength)",
"Vereinsbrett": "Club", "Nussbaum": "Walnut", "Schiefer": "Slate", "Marmor": "Marble", "Nacht": "Night",
"Der Bauer": "The pawn", "Der Springer": "The knight", "Der Läufer": "The bishop", "Der Turm": "The rook", "Die Dame": "The queen",
"hängende Figur": "hanging piece", "Matt übersehen": "overlooked mate", "Gabel übersehen": "overlooked fork",
"Gewinn verpasst": "missed win", "Gabel verpasst": "missed fork", "Matt verpasst": "missed mate",
"Zeitnot": "Time trouble", "zu schnell gespielt": "played too fast",
"Figur ungedeckt gelassen": "Left a piece hanging", "Matt zugelassen": "Allowed mate", "Gabel zugelassen": "Allowed a fork",
"Materialgewinn verpasst": "Missed winning material", "in Zeitnot": "In time trouble", "nach ≤ 3 s gespielt": "Played in ≤ 3 s",
"Insights über mehr als {n} Partien gibt es mit Pro.": "Insights across more than {n} games come with Pro.",
"Das Tageslimit von {n} Trainer-Aufgaben ist erreicht. Mit Pro trainierst du unbegrenzt.": "You've reached today's limit of {n} puzzles. Pro gives you unlimited training.",
"Der Auto-Import neuer Partien ist eine Pro-Funktion.": "Auto-importing new games is a Pro feature.",
"Review-Tiefen über {n} gibt es mit Pro.": "Review depths above {n} come with Pro.",
"Dieses Brett-Design gehört zu Pro.": "This board theme is part of Pro.",
"Mit Pro teilst du ohne Wasserzeichen.": "With Pro you share without a watermark.",
"Alle Werkzeuge, um schneller besser zu werden.": "Every tool to improve faster.",
"Hängende Figuren": "Hanging pieces",
"{c} von {n} Fehlern ließen eine Figur ungedeckt stehen. Frag dich vor jedem Zug: Was kann mein Gegner jetzt schlagen?": "{c} of {n} mistakes left a piece unprotected. Before every move, ask: what can my opponent take now?",
"Verpasste Taktik": "Missed tactics",
"{c} von {n} Fehlern waren verpasste Gewinne – Gabeln, Materialgewinn oder Matt. Genau diese Stellungen übt der Trainer.": "{c} of {n} mistakes were missed wins – forks, winning material or mate. The trainer drills exactly these positions.",
"Mattgefahr übersehen": "Missed mating threats",
"{c} Fehler ließen ein Matt zu. Prüfe vor jedem Zug alle Schachgebote und Schlagzüge des Gegners.": "{c} mistakes allowed mate. Before every move, check all of your opponent's checks and captures.",
"Gabeln zugelassen": "Allowed forks",
"{c} Fehler erlaubten eine Gabel. Achte auf Springerfelder und ungedeckte Figuren, die gleichzeitig angegriffen werden können.": "{c} mistakes allowed a fork. Watch knight squares and loose pieces that can be attacked at the same time.",
"{c} von {n} Fehlern passierten mit weniger als 30 Sekunden auf der Uhr. Spiel die Eröffnung zügiger, damit Zeit für die kritischen Momente bleibt.": "{c} of {n} mistakes happened with less than 30 seconds on the clock. Play the opening faster to save time for critical moments.",
"Zu schnell gespielt": "Playing too fast",
"{c} von {n} Fehlern kamen nach höchstens 3 Sekunden. Nimm dir in kritischen Momenten bewusst zehn Sekunden.": "{c} of {n} mistakes came after 3 seconds or less. Take a deliberate ten seconds in critical moments.",
"Im Endspiel spielst du mit {a} % deutlich ungenauer als im Schnitt ({o} %). Übe Grundendspiele: Turm-, Bauern- und Damenendspiele.": "In the endgame your accuracy drops to {a}% (average {o}%). Practise basic endgames: rook, pawn and queen endings.",
"In der Eröffnung liegt deine Genauigkeit bei {a} % (sonst {o} %). Lerne die ersten acht bis zehn Züge deiner Hauptsysteme.": "Your opening accuracy is {a}% (overall {o}%). Learn the first eight to ten moves of your main systems.",
"Schwache Eröffnung": "Weak opening",
"Mit {name} ({color}) holst du nur {s} der Punkte aus {g} Partien. Lerne die typischen Pläne oder wechsle das System.": "With the {name} ({color}) you score only {s} of the points in {g} games. Learn the typical plans or switch systems.",
"Patzer": "Blunder",
"Im Schnitt {b} Patzer pro Partie. Ein kurzer Blunder-Check vor jedem Zug halbiert das oft.": "{b} blunders per game on average. A quick blunder check before every move often halves that.",
"ist brillant": "is brilliant", "ist großartig": "is a great move", "ist der beste Zug": "is the best move", "ist exzellent": "is excellent",
"ist gut": "is good", "ist Theorie": "is book", "war erzwungen": "was forced", "ist eine Ungenauigkeit": "is an inaccuracy",
"ist ein Fehler": "is a mistake", "verpasst eine Chance": "is a miss", "ist ein Patzer": "is a blunder",
"Zieh mit einem Bauern (von {sq}).": "Move a pawn (from {sq}).", "Zieh mit dem Springer (von {sq}).": "Move the knight (from {sq}).",
"Zieh mit dem Läufer (von {sq}).": "Move the bishop (from {sq}).", "Zieh mit dem Turm (von {sq}).": "Move the rook (from {sq}).",
"Zieh mit der Dame (von {sq}).": "Move the queen (from {sq}).", "Zieh mit dem König (von {sq}).": "Move the king (from {sq}).",
"Brillant": "Brilliant", "Großartig": "Great", "Bester Zug": "Best move", "Exzellent": "Excellent", "Gut": "Good",
"Theorie": "Book", "Erzwungen": "Forced", "Ungenauigkeit": "Inaccuracy", "Fehler": "Mistake", "Verpasst": "Miss",
"Fehler des Gegners nicht bestraft": "Didn't punish the opponent's mistake",
"Bullet": "Bullet", "Blitz": "Blitz", "Schnellschach": "Rapid", "Klassisch": "Classical",
"NNUE": "NNUE", "Kompatibilitätsmodus": "compatibility mode",
"Analyse": "Analysis", "Spielen": "Play", "Insights": "Insights", "Trainer": "Trainer",
"Partie laden": "Load game", "Neue Partie": "New game", "Besten Zug spielen": "Play best move",
"Ich spiele": "I play", "Stärke der KI": "AI strength", "Hinweise zeigen (bester Zug und Linien)": "Show hints (best move and lines)",
"Neue Partie gegen KI": "New game vs. AI", "Zug zurücknehmen": "Take back",
"Taktik-Trainer": "Tactics trainer", "Training starten": "Start training", "Aufgaben sammeln": "Collect puzzles",
"Du analysierst eine Variante. Die Partie ist gespeichert.": "You are analysing a variation. The game is saved.",
"Partieformular": "Scoresheet", "PGN kopieren": "Copy PGN", "Schlüsselmomente": "Key moments", "Uhr": "Clock",
"Fehler trainieren": "Practise mistakes", "Review teilen": "Share review", "Einstellungen": "Settings",
"Live-Tiefe": "Live depth", "Review-Tiefe": "Review depth", "Engine-Linien": "Engine lines", "Notation": "Notation",
"Deutsch (S, L, T, D)": "German (S, L, T, D)", "Englisch (N, B, R, Q)": "English (N, B, R, Q)",
"Brett": "Board", "Zugtöne": "Move sounds", "Pfeil für den besten Zug": "Arrow for the best move",
"Pfeil für den zweitbesten Zug": "Arrow for the second-best move", "Pfeil „besser war …“ nach Fehlern": "“Better was …” arrow after mistakes",
"Bewertungs-Symbol auf dem Brett": "Rating icon on the board", "Ganze Partie automatisch bewerten": "Rate the whole game automatically",
"Engine: Stockfish 18 (GPLv3).": "Engine: Stockfish 18 (GPLv3).", "Lizenzen": "Licences", "Impressum": "Legal notice", "Datenschutz": "Privacy",
"Fair Play: Zugradar ist für Analyse, Training und Partien gegen die KI gedacht. Engine-Hilfe in laufenden Partien gegen Menschen ist auf allen Plattformen verboten.": "Fair play: Zugradar is built for analysis, training and games against the AI. Engine help in ongoing games against humans is forbidden on every platform.",
"Deine Insights": "Your insights", "Partien analysieren": "Analyse games", "Abbrechen": "Cancel",
"Meine Partien": "My games", "PGN / FEN": "PGN / FEN", "Partien holen": "Fetch games",
"Neue Partien automatisch laden, sobald sie beendet sind": "Load new games automatically as soon as they finish",
"Nur beendete Partien, über die öffentlichen Schnittstellen von chess.com und lichess, ohne Login. Laufende Partien liest Zugradar grundsätzlich nicht mit – Engine-Hilfe während einer Partie gegen Menschen ist Betrug.": "Finished games only, via the public chess.com and lichess APIs, no login. Zugradar never reads ongoing games – engine help during a game against humans is cheating.",
"PGN aus chess.com oder lichess (Partie → Teilen → PGN) oder eine FEN einfügen. Du kannst auch einfach irgendwo auf der Seite einfügen (Strg+V).": "Paste a PGN from chess.com or lichess (game → share → PGN) or a FEN. You can also just paste anywhere on the page (Ctrl+V).",
"Beispiel: Kasparow – Topalow 1999": "Example: Kasparov – Topalov 1999",
"Laden": "Load", "Schließen": "Close", "Pro kaufen": "Buy Pro", "7 Tage kostenlos testen": "Try free for 7 days",
"Lizenzschlüssel eingeben": "Enter licence key", "Aktivieren": "Activate", "Lizenz auf diesem Gerät abmelden": "Remove licence from this device",
"Bereiche": "Sections", "Auto-Import deiner beendeten Partien": "Auto-import of your finished games", "Sprache": "Language",
"Brett drehen (F)": "Flip board (F)", "Brett drehen": "Flip board", "Zum Anfang (Pos1)": "To start (Home)", "Zum Anfang": "To start",
"Zurück (←)": "Back (←)", "Zug zurück": "Previous move", "Vor (→)": "Forward (→)", "Zug vor": "Next move",
"Zum Ende (Ende)": "To end (End)", "Zum Ende": "To end", "Besten Zug ausführen (Leertaste)": "Play the best move (Space)",
"Anzahl Partien": "Number of games", "Quelle": "Source", "Plattform": "Platform", "Benutzername": "Username",
"Lizenzschlüssel aus der Kauf-E-Mail": "Licence key from your purchase email", "Lizenzschlüssel": "Licence key",
"<b>Insights über bis zu 100 Partien</b> – Genauigkeit, Phasen, Zeitnot, Eröffnungen und deine drei größten Baustellen.": "<b>Insights across up to 100 games</b> – accuracy, phases, time trouble, openings and your three biggest weak spots.",
"<b>Unbegrenzter Taktik-Trainer</b> aus deinen eigenen Fehlern, mit Wiederholung im richtigen Abstand.": "<b>Unlimited tactics trainer</b> built from your own mistakes, with spaced repetition.",
"<b>Auto-Import:</b> Jede beendete Partie ist analysiert, bevor du zurück bist.": "<b>Auto-import:</b> every finished game is analysed before you're back.",
"<b>Tiefere Analyse</b> (Review bis Tiefe 22), alle Brett-Designs, Teilen ohne Wasserzeichen.": "<b>Deeper analysis</b> (review up to depth 22), all board themes, sharing without a watermark.",
# Hilfe, Willkommen, Datensicherung
"Zug zurück / vor": "Previous / next move", "Pos1": "Home", "Ende": "End", "Zum Anfang / zum Ende": "To start / to end",
"Leertaste": "Space", "Dialog oder Training beenden": "Close dialog or stop training",
"Fragen, Probleme oder Wünsche? Schreib an": "Questions, problems or ideas? Write to", "Kontakt: siehe": "Contact: see",
"Dein Browser speichert keine Daten (privater Modus?). Es gibt nichts zu sichern.": "Your browser doesn't store any data (private mode?). There is nothing to back up.",
"Gesichert: {g}, {p}.": "Backed up: {g}, {p}.", "1 Partie": "1 game", "{n} Partien": "{n} games", "1 Trainer-Aufgabe": "1 trainer puzzle", "{n} Trainer-Aufgaben": "{n} trainer puzzles",
"Die Sicherung konnte nicht gespeichert werden.": "The backup could not be saved.",
"Das ist keine Zugradar-Sicherung.": "This is not a Zugradar backup.",
"Die Sicherung vom {d} ersetzt deine jetzigen Partien, Trainer-Fortschritte und Einstellungen. Fortfahren?": "The backup from {d} replaces your current games, trainer progress and settings. Continue?",
"Wiederherstellen fehlgeschlagen: Der Speicher des Browsers ist voll oder gesperrt.": "Restore failed: the browser's storage is full or blocked.",
"Die Datei konnte nicht gelesen werden.": "The file could not be read.",
"Willkommen bei Zugradar": "Welcome to Zugradar",
"Stockfish 18 bewertet jeden Zug – von brillant (!!) bis Patzer (??) – und erklärt in Klartext, was besser gewesen wäre. Auf dem Brett siehst du ein Beispiel: Kasparows berühmtes Turmopfer 24.Txd4!! gegen Topalow.": "Stockfish 18 rates every move – from brilliant (!!) to blunder (??) – and explains in plain words what would have been better. The board shows an example: Kasparov's famous rook sacrifice 24.Rxd4!! against Topalov.",
"Meine Partien laden": "Load my games", "Gegen die KI spielen": "Play the AI", "So funktioniert’s": "How it works",
"Deine Daten (Partien, Trainer, Einstellungen) liegen nur auf diesem Gerät.": "Your data (games, trainer, settings) is stored on this device only.",
"Sichern": "Back up", "Wiederherstellen": "Restore", "Hilfe": "Help", "In drei Schritten": "In three steps",
"Die Symbole": "The symbols", "Tastenkürzel": "Keyboard shortcuts", "Deine Daten": "Your data",
"Alles bleibt auf deinem Gerät: kein Konto, keine Cookies, keine Tracker. Unter „Einstellungen“ sicherst du Partien und Trainer-Fortschritt als Datei und stellst sie auf einem anderen Gerät wieder her.": "Everything stays on your device: no account, no cookies, no trackers. Under “Settings” you can back up your games and trainer progress as a file and restore them on another device.",
"Fair Play": "Fair play",
"Zugradar liest nie laufende Partien. Analysiere nach der Partie – Engine-Hilfe während einer Partie gegen Menschen ist Betrug.": "Zugradar never reads ongoing games. Analyse after the game – engine help during a game against humans is cheating.",
"Support": "Support",
"<b>Partie laden:</b> Benutzernamen von chess.com oder lichess eingeben oder eine PGN einfügen.": "<b>Load a game:</b> enter your chess.com or lichess username or paste a PGN.",
"<b>Zug für Zug durchgehen:</b> Jeder Zug bekommt ein Symbol. Der Coach erklärt Fehler und zeigt den besseren Zug.": "<b>Step through it:</b> every move gets a symbol. The coach explains mistakes and shows the better move.",
"<b>Besser werden:</b> Fehler der Partie nachspielen, Insights über viele Partien ansehen, im Trainer wiederholen.": "<b>Get better:</b> replay your mistakes, check insights across many games, repeat them in the trainer.",
"Ein gutes Opfer: der beste oder fast beste Zug, bei dem du Material hergibst.": "A sound sacrifice: the best or nearly best move, giving up material.",
"Der einzige gute Zug in einer kritischen Stellung.": "The only good move in a critical position.",
"Der Zug, den Stockfish selbst spielt.": "The move Stockfish itself plays.",
"Fast so gut wie der beste Zug.": "Almost as good as the best move.",
"Solider Zug mit kleinem Verlust.": "A solid move with a small loss.",
"Bekannte Eröffnungstheorie.": "Known opening theory.",
"Der einzige legale Zug.": "The only legal move.",
"Kleiner Verlust an Gewinnchance.": "A small loss of winning chances.",
"Deutlicher Verlust an Gewinnchance.": "A clear loss of winning chances.",
"Ein Matt oder ein Fehler des Gegners wurde nicht genutzt.": "A mate or an opponent's mistake was not taken.",
"Schwerer Fehler, der oft die Partie kostet.": "A serious mistake that often costs the game.",
# Remis-Regeln
"Dreifache Stellungswiederholung": "Threefold repetition", "50-Züge-Regel": "50-move rule",
"Damit steht dieselbe Stellung zum dritten Mal auf dem Brett – Remis, obwohl du besser standest.": "This brings the same position onto the board for the third time – a draw, although you were better.",
"Damit greift die 50-Züge-Regel – Remis, obwohl du besser standest. Ein Bauernzug oder Schlagzug hätte die Zählung zurückgesetzt.": "This triggers the 50-move rule – a draw, although you were better. A pawn move or capture would have reset the count.",
# Konnektor
"Hier ist die Verbindung gesperrt": "Connections are blocked here",
"In eingebetteten Vorschauen (z. B. auf claude.ai) blockiert der Browser jede Verbindung zu chess.com und lichess. Auf der Zugradar-Website lädt die App deine Partien direkt.": "In embedded previews (e.g. on claude.ai) the browser blocks every connection to chess.com and lichess. On the Zugradar website the app loads your games directly.",
"Zugradar-Website öffnen": "Open the Zugradar website", "Stattdessen PGN einfügen": "Paste a PGN instead",
"Diese Seite darf keine Verbindung zu {s} aufbauen (z. B. in einer Vorschau). Öffne Zugradar auf der eigenen Website – oder füge die PGN deiner Partie ein.": "This page is not allowed to connect to {s} (e.g. in a preview). Open Zugradar on its own website – or paste your game's PGN.",
"Benutzer „{u}“ gibt es auf {s} nicht. Stimmt die Schreibweise?": "There is no user “{u}” on {s}. Is the spelling right?",
"Das sieht nicht wie ein Benutzername aus. Gib nur den Namen ein (oder den Link zu deinem Profil).": "That doesn't look like a username. Enter just the name (or the link to your profile).",
"Keine beendeten Partien von {u} in den letzten 6 Monaten gefunden.": "No finished games by {u} in the last 6 months.",
# Leistung und Fazit
"Grobe Schätzung aus dem durchschnittlichen Bauernverlust pro Zug (ACPL {x}). Eine einzelne Partie ist nur ein Anhaltspunkt.": "Rough estimate from the average centipawn loss per move (ACPL {x}). A single game is only an indication.",
"Leistung ≈ {e}": "Performance ≈ {e}", "Fazit": "Summary",
"in der Eröffnung": "in the opening", "im Mittelspiel": "in the middlegame", "im Endspiel": "in the endgame",
"Am stärksten warst du {a} ({x}), am schwächsten {b} ({y}).": "You were strongest {a} ({x}) and weakest {b} ({y}).",
"{n} war {a} am stärksten ({x}), {b} am schwächsten ({y}).": "{n} was strongest {a} ({x}) and weakest {b} ({y}).",
"Dein teuerster Zug: {m} (Gewinnchance −{l} %).": "Your most costly move: {m} (winning chances −{l}%).",
"Teuerster Zug von {n}: {m} (Gewinnchance −{l} %).": "Most costly move by {n}: {m} (winning chances −{l}%).",
"Du hast keinen Fehler gemacht und keine Chance verpasst.": "You made no mistakes and missed no chances.",
"{n} hat keinen Fehler gemacht und keine Chance verpasst.": "{n} made no mistakes and missed no chances.",
"Dazu: {x}.": "Plus: {x}.", "{n}× brillant": "{n}× brilliant", "{n}× großartig": "{n}× great",
"Deine Leistung entsprach etwa {e} Elo.": "Your play was worth about {e} Elo.",
"Leistung von {n}: etwa {e} Elo.": "Performance of {n}: about {e} Elo.",
# Drohung
"Was droht? Zeigt den Zug, den der Gegner jetzt spielen würde (T)": "What's the threat? Shows the move your opponent would play now (T)",
"Drohung zeigen": "Show threat", "Was droht? (Drohung zeigen)": "What's the threat? (show threat)",
"Partie beendet – keine Drohung.": "Game over – no threat.",
"Du stehst im Schach – das ist die Drohung.": "You are in check – that is the threat.",
"Drohungen erscheinen, sobald Hinweise sichtbar sind.": "Threats appear as soon as hints are visible.",
"Suche, was {c} droht …": "Looking for what {c} threatens …",
"{c} droht gerade nichts Ernstes.": "{c} is not threatening anything serious right now.",
"{c} droht {m} – Matt in {n}.": "{c} threatens {m} – mate in {n}.",
"{c} droht {m} (gewinnt etwa {p} Bauern).": "{c} threatens {m} (wins about {p} pawns).",
# Hilfe: Formeln
"So rechnet Zugradar": "How Zugradar calculates",
"Grundlage ist die <b>Gewinnchance</b> vor und nach jedem Zug (Formel wie bei lichess). Kostet ein Zug weniger als 2 % Gewinnchance, ist er exzellent; ab 20 % ist es ein Patzer. <b>Brillant</b> heißt: (fast) bester Zug mit einem echten Materialopfer, das Stockfish bestätigt. Die <b>Leistung</b> kommt aus dem durchschnittlichen Bauernverlust pro Zug (ACPL): Elo ≈ 3100 · e<sup>−ACPL/100</sup>. Stockfish kennt den Partieverlauf und damit auch Remis durch Zugwiederholung.": "Everything is based on the <b>winning chances</b> before and after each move (same formula as lichess). A move that costs less than 2% is excellent; 20% or more is a blunder. <b>Brilliant</b> means: the (nearly) best move with a real material sacrifice that Stockfish confirms. <b>Performance</b> comes from the average centipawn loss per move (ACPL): Elo ≈ 3100 · e<sup>−ACPL/100</sup>. Stockfish knows the game history and therefore draws by repetition too.",
}
